// This file was generated by liblab | https://liblab.com/

package integrations

import "encoding/json"

type SlackStartInstall struct {
	// Slack app ID that the installation flow should use.
	AppId *string `json:"app_id,omitempty" required:"true"`
	// Optional override for the authorization URL returned to the client.
	AuthUrl *string `json:"auth_url,omitempty"`
	// Additional OAuth scopes to request during installation.
	ExtraScopes []string `json:"extra_scopes,omitempty"`
	// Custom redirect URL to use after OAuth completes.
	RedirectUrl *string `json:"redirect_url,omitempty"`
}

func (s *SlackStartInstall) GetAppId() *string {
	if s == nil {
		return nil
	}
	return s.AppId
}

func (s *SlackStartInstall) SetAppId(appId string) {
	s.AppId = &appId
}

func (s *SlackStartInstall) GetAuthUrl() *string {
	if s == nil {
		return nil
	}
	return s.AuthUrl
}

func (s *SlackStartInstall) SetAuthUrl(authUrl string) {
	s.AuthUrl = &authUrl
}

func (s *SlackStartInstall) GetExtraScopes() []string {
	if s == nil {
		return nil
	}
	return s.ExtraScopes
}

func (s *SlackStartInstall) SetExtraScopes(extraScopes []string) {
	s.ExtraScopes = extraScopes
}

func (s *SlackStartInstall) GetRedirectUrl() *string {
	if s == nil {
		return nil
	}
	return s.RedirectUrl
}

func (s *SlackStartInstall) SetRedirectUrl(redirectUrl string) {
	s.RedirectUrl = &redirectUrl
}

func (s SlackStartInstall) String() string {
	jsonData, err := json.MarshalIndent(s, "", "  ")
	if err != nil {
		return "error converting struct: SlackStartInstall to string"
	}
	return string(jsonData)
}
