// This file was generated by liblab | https://liblab.com/

package channels

import "encoding/json"

type CategoryDeliveryConfig struct {
	// Ordered channel steps the delivery planner should execute.
	Channels []CategoryDeliveryConfigChannels `json:"channels,omitempty" required:"true"`
	// Disables the plan so it cannot be executed.
	Disabled *bool `json:"disabled,omitempty"`
	// Unique identifier for this delivery plan.
	Key *string `json:"key,omitempty" required:"true" minLength:"3" pattern:"^[A-Za-z0-9_.\-:/]+$"`
}

func (c *CategoryDeliveryConfig) GetChannels() []CategoryDeliveryConfigChannels {
	if c == nil {
		return nil
	}
	return c.Channels
}

func (c *CategoryDeliveryConfig) SetChannels(channels []CategoryDeliveryConfigChannels) {
	c.Channels = channels
}

func (c *CategoryDeliveryConfig) GetDisabled() *bool {
	if c == nil {
		return nil
	}
	return c.Disabled
}

func (c *CategoryDeliveryConfig) SetDisabled(disabled bool) {
	c.Disabled = &disabled
}

func (c *CategoryDeliveryConfig) GetKey() *string {
	if c == nil {
		return nil
	}
	return c.Key
}

func (c *CategoryDeliveryConfig) SetKey(key string) {
	c.Key = &key
}

func (c CategoryDeliveryConfig) String() string {
	jsonData, err := json.MarshalIndent(c, "", "  ")
	if err != nil {
		return "error converting struct: CategoryDeliveryConfig to string"
	}
	return string(jsonData)
}
