// This file was generated by liblab | https://liblab.com/

package shared

import "encoding/json"

type WebPushTokenPayload struct {
	// The push subscription URL obtained from PushSubscription.endpoint after calling registration.pushManager.subscribe(). This is the unique URL for this device that push messages will be sent to.
	Endpoint *string `json:"endpoint,omitempty" required:"true"`
	// The encryption keys from the PushSubscription.getKey() method, needed to encrypt push messages for this subscription.
	Keys *WebPushTokenPayloadKeys `json:"keys,omitempty" required:"true"`
}

func (w *WebPushTokenPayload) GetEndpoint() *string {
	if w == nil {
		return nil
	}
	return w.Endpoint
}

func (w *WebPushTokenPayload) SetEndpoint(endpoint string) {
	w.Endpoint = &endpoint
}

func (w *WebPushTokenPayload) GetKeys() *WebPushTokenPayloadKeys {
	if w == nil {
		return nil
	}
	return w.Keys
}

func (w *WebPushTokenPayload) SetKeys(keys WebPushTokenPayloadKeys) {
	w.Keys = &keys
}

func (w WebPushTokenPayload) String() string {
	jsonData, err := json.MarshalIndent(w, "", "  ")
	if err != nil {
		return "error converting struct: WebPushTokenPayload to string"
	}
	return string(jsonData)
}
