// This file was generated by liblab | https://liblab.com/

package clientconfig

// Environment constants define the available base URLs for different deployment environments.
// Use these constants when configuring the SDK client.
const (
	DEFAULT_ENVIRONMENT = "https://api.magicbell.com/v2"
)
