// This file was generated by liblab | https://liblab.com/

package integrations

import (
	"encoding/json"
	"github.com/magicbell/magicbell-go/pkg/project-client/internal/unmarshal"
	"github.com/magicbell/magicbell-go/pkg/project-client/util"
)

type MailgunConfigPayloadFrom struct {
	// The email address to send from
	Email *string `json:"email,omitempty" required:"true"`
	// The name to send from
	Name *util.Nullable[string] `json:"name,omitempty"`
}

func (m *MailgunConfigPayloadFrom) GetEmail() *string {
	if m == nil {
		return nil
	}
	return m.Email
}

func (m *MailgunConfigPayloadFrom) SetEmail(email string) {
	m.Email = &email
}

func (m *MailgunConfigPayloadFrom) GetName() *util.Nullable[string] {
	if m == nil {
		return nil
	}
	return m.Name
}

func (m *MailgunConfigPayloadFrom) SetName(name util.Nullable[string]) {
	m.Name = &name
}

func (m *MailgunConfigPayloadFrom) SetNameNull() {
	m.Name = &util.Nullable[string]{IsNull: true}
}

func (m MailgunConfigPayloadFrom) String() string {
	jsonData, err := json.MarshalIndent(m, "", "  ")
	if err != nil {
		return "error converting struct: MailgunConfigPayloadFrom to string"
	}
	return string(jsonData)
}

func (m *MailgunConfigPayloadFrom) UnmarshalJSON(data []byte) error {
	return unmarshal.UnmarshalNullable(data, m)
}
