// This file was generated by liblab | https://liblab.com/

package integrations

import (
	"encoding/json"
	"github.com/magicbell/magicbell-go/pkg/project-client/internal/unmarshal"
	"github.com/magicbell/magicbell-go/pkg/project-client/util"
)

type SendgridConfigPayloadReplyTo struct {
	// The email address to reply to
	Email *string `json:"email,omitempty" required:"true"`
	// The name to reply to
	Name *util.Nullable[string] `json:"name,omitempty"`
}

func (s *SendgridConfigPayloadReplyTo) GetEmail() *string {
	if s == nil {
		return nil
	}
	return s.Email
}

func (s *SendgridConfigPayloadReplyTo) SetEmail(email string) {
	s.Email = &email
}

func (s *SendgridConfigPayloadReplyTo) GetName() *util.Nullable[string] {
	if s == nil {
		return nil
	}
	return s.Name
}

func (s *SendgridConfigPayloadReplyTo) SetName(name util.Nullable[string]) {
	s.Name = &name
}

func (s *SendgridConfigPayloadReplyTo) SetNameNull() {
	s.Name = &util.Nullable[string]{IsNull: true}
}

func (s SendgridConfigPayloadReplyTo) String() string {
	jsonData, err := json.MarshalIndent(s, "", "  ")
	if err != nil {
		return "error converting struct: SendgridConfigPayloadReplyTo to string"
	}
	return string(jsonData)
}

func (s *SendgridConfigPayloadReplyTo) UnmarshalJSON(data []byte) error {
	return unmarshal.UnmarshalNullable(data, s)
}
