// This file was generated by liblab | https://liblab.com/

package integrations

import "encoding/json"

type SesConfigPayload struct {
	From *SesConfigPayloadFrom `json:"from,omitempty"`
	// AWS Access Key ID
	KeyId *string `json:"key_id,omitempty" required:"true" minLength:"1"`
	// AWS Region
	Region *string `json:"region,omitempty" required:"true" minLength:"1"`
	// AWS Secret Key
	SecretKey *string `json:"secret_key,omitempty" required:"true" minLength:"1"`
}

func (s *SesConfigPayload) GetFrom() *SesConfigPayloadFrom {
	if s == nil {
		return nil
	}
	return s.From
}

func (s *SesConfigPayload) SetFrom(from SesConfigPayloadFrom) {
	s.From = &from
}

func (s *SesConfigPayload) GetKeyId() *string {
	if s == nil {
		return nil
	}
	return s.KeyId
}

func (s *SesConfigPayload) SetKeyId(keyId string) {
	s.KeyId = &keyId
}

func (s *SesConfigPayload) GetRegion() *string {
	if s == nil {
		return nil
	}
	return s.Region
}

func (s *SesConfigPayload) SetRegion(region string) {
	s.Region = &region
}

func (s *SesConfigPayload) GetSecretKey() *string {
	if s == nil {
		return nil
	}
	return s.SecretKey
}

func (s *SesConfigPayload) SetSecretKey(secretKey string) {
	s.SecretKey = &secretKey
}

func (s SesConfigPayload) String() string {
	jsonData, err := json.MarshalIndent(s, "", "  ")
	if err != nil {
		return "error converting struct: SesConfigPayload to string"
	}
	return string(jsonData)
}
