// This file was generated by liblab | https://liblab.com/

package integrations

import "encoding/json"

type WebpushConfigPayload struct {
	// VAPID private key.
	PrivateKey *string `json:"private_key,omitempty" required:"true" maxLength:"128" minLength:"8"`
	// VAPID public key - read more at https://magicbell.com/tools/vapid-keys.
	PublicKey *string `json:"public_key,omitempty" required:"true" maxLength:"128" minLength:"8"`
}

func (w *WebpushConfigPayload) GetPrivateKey() *string {
	if w == nil {
		return nil
	}
	return w.PrivateKey
}

func (w *WebpushConfigPayload) SetPrivateKey(privateKey string) {
	w.PrivateKey = &privateKey
}

func (w *WebpushConfigPayload) GetPublicKey() *string {
	if w == nil {
		return nil
	}
	return w.PublicKey
}

func (w *WebpushConfigPayload) SetPublicKey(publicKey string) {
	w.PublicKey = &publicKey
}

func (w WebpushConfigPayload) String() string {
	jsonData, err := json.MarshalIndent(w, "", "  ")
	if err != nil {
		return "error converting struct: WebpushConfigPayload to string"
	}
	return string(jsonData)
}
