// This file was generated by liblab | https://liblab.com/

package channels

import (
	"encoding/json"
	"github.com/magicbell/magicbell-go/pkg/user-client/internal/unmarshal"
	"github.com/magicbell/magicbell-go/pkg/user-client/util"
)

type WebPushToken struct {
	// The timestamp when the token was created.
	CreatedAt *string `json:"created_at,omitempty" required:"true"`
	// The timestamp when the token was discarded, if applicable.
	DiscardedAt *util.Nullable[string] `json:"discarded_at,omitempty"`
	// The push subscription URL obtained from PushSubscription.endpoint after calling registration.pushManager.subscribe(). This is the unique URL for this device that push messages will be sent to.
	Endpoint *string `json:"endpoint,omitempty" required:"true"`
	// The unique identifier for the token.
	Id *string `json:"id,omitempty" required:"true"`
	// The encryption keys from the PushSubscription.getKey() method, needed to encrypt push messages for this subscription.
	Keys *WebPushTokenKeys `json:"keys,omitempty" required:"true"`
	// The timestamp when the token metadata last changed.
	UpdatedAt *util.Nullable[string] `json:"updated_at,omitempty"`
}

func (w *WebPushToken) GetCreatedAt() *string {
	if w == nil {
		return nil
	}
	return w.CreatedAt
}

func (w *WebPushToken) SetCreatedAt(createdAt string) {
	w.CreatedAt = &createdAt
}

func (w *WebPushToken) GetDiscardedAt() *util.Nullable[string] {
	if w == nil {
		return nil
	}
	return w.DiscardedAt
}

func (w *WebPushToken) SetDiscardedAt(discardedAt util.Nullable[string]) {
	w.DiscardedAt = &discardedAt
}

func (w *WebPushToken) SetDiscardedAtNull() {
	w.DiscardedAt = &util.Nullable[string]{IsNull: true}
}

func (w *WebPushToken) GetEndpoint() *string {
	if w == nil {
		return nil
	}
	return w.Endpoint
}

func (w *WebPushToken) SetEndpoint(endpoint string) {
	w.Endpoint = &endpoint
}

func (w *WebPushToken) GetId() *string {
	if w == nil {
		return nil
	}
	return w.Id
}

func (w *WebPushToken) SetId(id string) {
	w.Id = &id
}

func (w *WebPushToken) GetKeys() *WebPushTokenKeys {
	if w == nil {
		return nil
	}
	return w.Keys
}

func (w *WebPushToken) SetKeys(keys WebPushTokenKeys) {
	w.Keys = &keys
}

func (w *WebPushToken) GetUpdatedAt() *util.Nullable[string] {
	if w == nil {
		return nil
	}
	return w.UpdatedAt
}

func (w *WebPushToken) SetUpdatedAt(updatedAt util.Nullable[string]) {
	w.UpdatedAt = &updatedAt
}

func (w *WebPushToken) SetUpdatedAtNull() {
	w.UpdatedAt = &util.Nullable[string]{IsNull: true}
}

func (w WebPushToken) String() string {
	jsonData, err := json.MarshalIndent(w, "", "  ")
	if err != nil {
		return "error converting struct: WebPushToken to string"
	}
	return string(jsonData)
}

func (w *WebPushToken) UnmarshalJSON(data []byte) error {
	return unmarshal.UnmarshalNullable(data, w)
}
