// This file was generated by liblab | https://liblab.com/

package client

import (
	"github.com/magicbell/magicbell-go/pkg/user-client/internal/clients/rest/hooks"
	"github.com/magicbell/magicbell-go/pkg/user-client/internal/configmanager"
	"github.com/magicbell/magicbell-go/pkg/user-client/channels"
	"github.com/magicbell/magicbell-go/pkg/user-client/clientconfig"
	"github.com/magicbell/magicbell-go/pkg/user-client/integrations"
	"github.com/magicbell/magicbell-go/pkg/user-client/notifications"
	"time"
)

// Client is the main SDK client that provides access to all service endpoints.
// It manages configuration, authentication, and service instances with centralized settings.
type Client struct {
	Channels      *channels.ChannelsService
	Integrations  *integrations.IntegrationsService
	Notifications *notifications.NotificationsService
	manager       *configmanager.ConfigManager
}

func NewClient(config clientconfig.Config) *Client {
	channels := channels.NewChannelsService()
	integrations := integrations.NewIntegrationsService()
	notifications := notifications.NewNotificationsService()

	manager := configmanager.NewConfigManager(config)
	hook := hooks.NewDefaultHook()
	channels.WithConfigManager(manager)
	integrations.WithConfigManager(manager)
	notifications.WithConfigManager(manager)
	channels.WithHook(hook)
	integrations.WithHook(hook)
	notifications.WithHook(hook)

	return &Client{
		Channels:      channels,
		Integrations:  integrations,
		Notifications: notifications,
		manager:       manager,
	}
}

func (c *Client) SetBaseUrl(baseUrl string) {
	c.manager.SetBaseUrl(baseUrl)
}

func (c *Client) SetTimeout(timeout time.Duration) {
	c.manager.SetTimeout(timeout)
}

func (c *Client) SetAccessToken(accessToken string) {
	c.manager.SetAccessToken(accessToken)
}

// c029837e0e474b76bc487506e8799df5e3335891efe4fb02bda7a1441840310c
