// This file was generated by liblab | https://liblab.com/

package main

import (
	"bufio"
	"fmt"
	"os"
	"strings"

	"context"
	"github.com/magicbell/magicbell-go/pkg/user-client/channels"
	"github.com/magicbell/magicbell-go/pkg/user-client/client"
	"github.com/magicbell/magicbell-go/pkg/user-client/clientconfig"
	"github.com/magicbell/magicbell-go/pkg/user-client/util"
)

func main() {
	loadEnv()

	config := clientconfig.NewConfig()
	client := client.NewClient(config)

	params := channels.ListInboxTokensRequestParams{
		Limit:         util.ToPointer(int64(8)),
		StartingAfter: util.ToPointer("starting_after"),
		EndingBefore:  util.ToPointer("ending_before"),
	}

	response, err := client.Channels.ListInboxTokens(context.Background(), params)
	if err != nil {
		panic(err)
	}
	fmt.Printf("%+v", response)
}

func loadEnv() error {
	file, err := os.Open(".env")
	if err != nil {
		return err
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := scanner.Text()
		parts := strings.SplitN(line, "=", 2)
		if len(parts) != 2 {
			continue
		}
		key := strings.TrimSpace(parts[0])
		value := strings.TrimSpace(parts[1])
		os.Setenv(key, value)
	}

	if err := scanner.Err(); err != nil {
		return err
	}

	return nil
}
